# Generated by Django 4.1.6 on 2023-02-13 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reg',
        ),
    ]
